import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {CalendarDays, MapPin, Clock3, Share2, Sparkles, Users, Bell, ArrowUpRight} from 'lucide-react';
import './styles.css';

const API='http://localhost:8000';
type Event={id:string;title:string;venue:string;city:string;date:string;time:string;image_url:string;category:string;description:string;friends_attending:number;user_status?:'interested'|'going'|null};
type User={id:string;name:string;email:string;city:string};
async function api(path:string, options:RequestInit={}){const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json','X-User-Id':localStorage.userId||'',...(options.headers||{})}}); if(!r.ok) throw new Error((await r.json()).detail||'Request failed'); return r.json();}

function App(){
 const [user,setUser]=useState<User|null>(null); const [events,setEvents]=useState<Event[]>([]); const [city,setCity]=useState('New York'); const [active,setActive]=useState<'discover'|'dashboard'>('discover'); const [profileOpen,setProfileOpen]=useState(false); const [notice,setNotice]=useState('');
 useEffect(()=>{const id=localStorage.userId;if(id) api('/api/users/'+id).then(setUser).catch(()=>localStorage.removeItem('userId'));},[]);
 useEffect(()=>{if(user) load();},[user,city]);
 async function load(){setEvents(await api('/api/events?city='+encodeURIComponent(city)));}
 async function createProfile(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const u=await api('/api/users',{method:'POST',body:JSON.stringify({name:f.get('name'),email:f.get('email'),city})});localStorage.userId=u.id;setUser(u);setProfileOpen(false);}
 async function rsvp(event:Event){try{await api('/api/rsvp',{method:'POST',body:JSON.stringify({event_id:event.id,status:'going',reminder_enabled:true,minutes_before:60})});setNotice('You are going — reminder set for 1 hour before.');load();}catch(e){setNotice((e as Error).message);}}
 async function share(event:Event){try{const x=await api('/api/share?event_id='+event.id,{method:'POST'});await navigator.clipboard?.writeText(x.url);setNotice('Share link copied to clipboard.');}catch(e){setNotice((e as Error).message);}}
 const days=useMemo(()=>events.reduce<Record<string,number>>((a,e)=>(a[e.date]=(a[e.date]||0)+1,a),{}),[events]);
 return <div className="app"><header><div className="brand"><span className="mark"><Sparkles size={17}/></span><span>evently</span></div><nav><button className={active==='discover'?'active':''} onClick={()=>setActive('discover')}>Discover</button><button className={active==='dashboard'?'active':''} onClick={()=>setActive('dashboard')}>My plans</button></nav><button className="profile" onClick={()=>setProfileOpen(true)}>{user?<><span className="avatar">{user.name[0]}</span>{user.name.split(' ')[0]}</>: 'Create profile'}</button></header>
 <main><section className="hero"><div><p className="eyebrow">YOUR CITY, YOUR CALENDAR</p><h1>Make room for<br/><em>something memorable.</em></h1><p className="sub">Find the events worth leaving the house for — and bring your people along.</p></div><div className="hero-note"><span className="live-dot"></span><b>Live social signal</b><small>Friends attending updates in real time</small></div></section>
 <div className="toolbar"><div className="city-select"><MapPin size={16}/><select value={city} onChange={e=>setCity(e.target.value)}><option>New York</option><option>London</option><option>All</option></select></div><div className="view-label"><CalendarDays size={17}/> September 2026</div></div>
 {active==='discover'?<><section className="calendar"><div className="calendar-head"><div><h2>September <span>2026</span></h2><p>Tap a date to explore what’s happening.</p></div><div className="legend"><i></i> Events nearby</div></div><div className="weekdays">{['MON','TUE','WED','THU','FRI','SAT','SUN'].map(x=><span>{x}</span>)}</div><div className="grid">{Array.from({length:30},(_,i)=>{const n=i+1;const date=`2026-09-${String(n).padStart(2,'0')}`;return <div className={'day '+(days[date]?'has-events':'')} key={date}><span>{n}</span>{days[date]&&<b>{days[date]}</b>}</div>})}</div></section><section className="feed"><div className="section-title"><div><p className="eyebrow">CURATED FOR YOU</p><h2>Coming up <span>near you</span></h2></div><span className="count">{events.length} events</span></div><div className="cards">{events.map(e=><article className="card" key={e.id}><img src={e.image_url}/><div className="card-body"><div className="tag">{e.category}</div><h3>{e.title}</h3><p className="description">{e.description}</p><div className="meta"><span><CalendarDays size={14}/>{e.date}</span><span><Clock3 size={14}/>{e.time}</span><span><MapPin size={14}/>{e.venue}</span></div><div className="card-actions"><button className={e.user_status?'going':''} onClick={()=>rsvp(e)}>{e.user_status==='going'?'Going ✓':'I’m interested'}</button><button className="icon-btn" onClick={()=>share(e)} title="Share"><Share2 size={16}/></button><span className="friends"><Users size={15}/>{e.friends_attending} friends</span></div></div></article>)}</div></section></>:<Dashboard user={user} events={events} />}</main>
 {notice&&<button className="toast" onClick={()=>setNotice('')}>{notice} ×</button>}{profileOpen&&<div className="modal-backdrop"><form className="modal" onSubmit={createProfile}><button type="button" className="close" onClick={()=>setProfileOpen(false)}>×</button><p className="eyebrow">WELCOME TO EVENTLY</p><h2>Tell us who’s coming.</h2><p>We use a lightweight profile for this demo. No password required.</p><label>Name<input name="name" required placeholder="Alex Morgan"/></label><label>Email<input name="email" type="email" required placeholder="alex@example.com"/></label><button className="primary">Start exploring <ArrowUpRight size={16}/></button></form></div>}</div>
}
function Dashboard({user,events}:{user:User|null;events:Event[]}){const mine=events.filter(e=>e.user_status);return <section className="dashboard"><div className="dashboard-intro"><p className="eyebrow">YOUR RSVP DASHBOARD</p><h1>{user?.name.split(' ')[0] || 'Your'} plans.</h1><p>Everything you’ve said yes to, in one place.</p></div>{mine.length?<div className="plan-list">{mine.map(e=><div className="plan"><div className="plan-date"><b>{new Date(e.date).getDate()}</b><small>{new Date(e.date).toLocaleDateString('en-US',{month:'short'}).toUpperCase()}</small></div><div><h3>{e.title}</h3><p>{e.venue} · {e.time}</p></div><span className="going-pill"><Bell size={14}/> Reminder on</span></div>)}</div>:<div className="empty"><Sparkles/><h2>Your next good idea is out there.</h2><p>RSVP to an event and it will appear here.</p></div>}</section>}
createRoot(document.getElementById('root')!).render(<App/>);
